pod 'VideoCore', :git => 'https://github.com/bellchen/VideoCore.git'
pod 'glm', :podspec => 'https://raw.githubusercontent.com/bellchen/GDLiveStreaming/master/glm.podspec'

target 'GDLiveStreaming_Example' do
  pod 'GDLiveStreaming', :path => '../'
end

target 'GDLiveStreaming_Tests' do
  pod 'GDLiveStreaming', :path => '../'
end
